version: '3'

services:
    web:
        image: nginx:alpine
        ports:
            - "8080:80"
        volumes:
            - ./code:/usr/share/nginx/html
            - ./site.conf:/etc/nginx/conf.d/default.conf
    php:
        image: php:7.2-fpm-alpine
        volumes:
            - ./code:/usr/share/nginx/html
