version: '3'
services:
    nginx:
        image: nginx:alpine
        ports: 
            - 4002:80
        volumes:
            - .:/usr/share/nginx/html
            - ./default.conf:/etc/nginx/conf.d/default.conf
    php:
        image: uumyheart/php:7.2
        volumes:
            - .:/usr/share/nginx/html
            - /Users/Garan/Downloads/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
networks:
  default:
    external:
      name: my_bridge