version: '3'
services:
    nginx:
        image: nginx:alpine
        ports: 
            - 4000:80
        volumes:
            - .:/usr/share/nginx/html
            - ./default.conf:/etc/nginx/conf.d/default.conf
    php:
        image: php:7.2-fpm-alpine
        volumes:
            - .:/usr/share/nginx/html